### ISSUE TITLE
贴吧第三方助手安装不了呀

### ISSUE THREAD

**Issue by Metalism666** [shitianshiwa/baidu-tieba-userscript#3]
**环境信息**

脚本名称: 贴吧助手 第三方修改
脚本版本:最新
运行环境:
出问题链接:  
**bug内容**

**复现方法**

**Comment by Metalism666** [comment]
前面写了一堆，点发布给吞了

由于greasy fork原版作者的脚本已经失效，来这里下载，但是今天突然无法使用，左键点击页面中的链接也无法下载

右键新建标签页提示：该网页无法正常运作raw.githubusercontent.com 未发送任何数据

即使翻墙也无法下载

**Comment by shitianshiwa** [comment]
> 前面写了一堆，点发布给吞了
> 
> 由于greasy fork原版作者的脚本已经失效，来这里下载，但是今天突然无法使用，左键点击页面中的链接也无法下载
> 
> 右键新建标签页提示：该网页无法正常运作raw.githubusercontent.com 未发送任何数据
> 
> 即使翻墙也无法下载 浏览器vivaldi win10系统

有个方法就是直接复制代码进行更新。。。

**Comment by shitianshiwa** [comment]
> 前面写了一堆，点发布给吞了
> 
> 由于greasy fork原版作者的脚本已经失效，来这里下载，但是今天突然无法使用，左键点击页面中的链接也无法下载
> 
> 右键新建标签页提示：该网页无法正常运作raw.githubusercontent.com 未发送任何数据
> 
> 即使翻墙也无法下载 浏览器vivaldi win10系统

原版应该也是因为原作者引用代码的授权等原因被举报掉了

**Comment by shitianshiwa** [comment]
https://openuserjs.org/scripts/shitianshiwa/%E8%B4%B4%E5%90%A7%E5%85%A8%E8%83%BD%E5%8A%A9%E6%89%8B(%E7%AC%AC%E4%B8%89%E6%96%B9%E4%BF%AE%E6%94%B9)
