### ISSUE TITLE
2.1.1835无法放大贴吧图片

### ISSUE THREAD

**Issue by MarsTLBAD** [shitianshiwa/baidu-tieba-userscript#7]
**环境信息**

脚本名称: 贴吧全能助手(第三方修改)
脚本版本: 2.1.1835
运行环境: win10 Chromium 86.0.4240.198
出问题链接:  百度贴吧任意帖子

**bug内容**

贴吧图片无法放大， 无论是双击还是单击，尝试修复无效

**复现方法**

**Comment by horizon98** [comment]
+1

日志如下：
![image](https://user-images.githubusercontent.com/48114360/158005076-ff18a628-06bc-4c60-a056-55784221053d.png)

`
userscript.html?name=%E8%B4%B4%E5%90%A7%E5%85%A8%E8%83%BD%E5%8A%A9%E6%89%8B(%E7%AC%AC%E4%B8%89%E6%96%B9%E4%BF%AE%E6%94%B9).user.js&id=bdd4bcb1-71d5-413e-ba0c-3fd94d6cd045:10518 图片放大设置 已执行 click,click,1,0,1,false
userscript.html?name=%E8%B4%B4%E5%90%A7%E5%85%A8%E8%83%BD%E5%8A%A9%E6%89%8B(%E7%AC%AC%E4%B8%89%E6%96%B9%E4%BF%AE%E6%94%B9).user.js&id=bdd4bcb1-71d5-413e-ba0c-3fd94d6cd045:10517 阻止贴吧图片原事件 已执行
userscript.html?name=%E8%B4%B4%E5%90%A7%E5%85%A8%E8%83%BD%E5%8A%A9%E6%89%8B(%E7%AC%AC%E4%B8%89%E6%96%B9%E4%BF%AE%E6%94%B9).user.js&id=bdd4bcb1-71d5-413e-ba0c-3fd94d6cd045:10517 图片创建 开始
userscript.html?name=%E8%B4%B4%E5%90%A7%E5%85%A8%E8%83%BD%E5%8A%A9%E6%89%8B(%E7%AC%AC%E4%B8%89%E6%96%B9%E4%BF%AE%E6%94%B9).user.js&id=bdd4bcb1-71d5-413e-ba0c-3fd94d6cd045:10518 图片地址获取 失败 http://tiebapic.baidu.com/forum/w%3D580/sign=4433fac34cf79052ef1f47363cf2d738/ae0076d98d1001e95d969ddffd0e7bec56e79780.jpg?tbpicau=2022-03-13-13_8a5e0254b452eb456570c58823d3788f`

**Comment by shitianshiwa** [comment]
待修
可以用这个代替（原作者）
https://greasyfork.org/zh-CN/scripts/20969-%E7%99%BE%E5%BA%A6%E8%B4%B4%E5%90%A7%E5%9B%BE%E7%89%87%E7%82%B9%E5%87%BB%E6%94%BE%E5%A4%A7
助手设置里面选‘看图模式屏蔽’即可

**Comment by n0099** [comment]
#11
